pipelines:
  branches:
    develop:
      - step:
          script:
            - apt-get install -y zip
            - zip -r application.zip .
            - pipe: atlassian/aws-code-deploy:0.2.7
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
                VERSION_LABEL: 'react-app-1.0.0'
            - pipe: atlassian/aws-code-deploy:0.2.7
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                WAIT: 'true'
                COMMAND: 'deploy'
                VERSION_LABEL: 'application-1.0.0'
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'