# image: atlassian/default-image:2
image: node:10.15.3

pipelines:
  pull-requests:
    "**":
      - step:
          name: Test
          caches:
            - node
          script:
            - npm install
            - npm run test:nowatch
      - step:
          name: Code linting
          script:
            - npm install
            - npm run lint
          caches:
            - node
  # default:
  #   - parallel:
  #       - step:
  #           name: Build and Test
  #           caches:
  #             - node
  #           script:
  #             - npm install
  #             - npm run test:nowatch
  #       - step:
  #           name: Code linting
  #           script:
  #             - npm install
  #             - npm run lint
  #           caches:
  #             - node
    # - step:
    #     name: Build
    #     script:
    #       - zip -r myapp.zip *
    #     artifacts:
    #       - myapp.zip

    # - step:
    #     name: Upload to S3
    #     services:
    #       - docker
    #     script:
    #       # Test upload
    #       - pipe: atlassian/aws-code-deploy:0.2.10
    #         variables:
    #           AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    #           AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    #           AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    #           S3_BUCKET: $S3_BUCKET
    #           COMMAND: "upload"
    #           APPLICATION_NAME: $APPLICATION_NAME
    #           ZIP_FILE: "myapp.zip"

    # - step:
    #     name: Deploy with CodeDeploy
    #     deployment: production
    #     services:
    #     - docker
    #     script:
    #     - echo "Environment ${REPOSITORY_VARIABLE}"
    #     # Test upload
    #     - pipe: atlassian/aws-code-deploy:0.2.10
    #       variables:
    #         AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    #         AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    #         AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    #         S3_BUCKET: $S3_BUCKET
    #         COMMAND: "deploy"
    #         APPLICATION_NAME: $APPLICATION_NAME
    #         DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
    #         IGNORE_APPLICATION_STOP_FAILURES: "true"
    #         FILE_EXISTS_BEHAVIOR: "OVERWRITE"
    #         WAIT: "true"